#!/usr/bin/env python3
"""Generate examples/gemini-user-policies/reviewer-network-deny.toml.

The policy is generated rather than hand-written because Gemini CLI 0.62.0
puts tight constraints on `commandRegex` and every rule is repeated for each
reviewer role:

- Gemini matches commandRegex against the JSON-encoded tool args, after the
  literal prefix `"command":"`. A regex can therefore only match at the start
  of a command (the engine checks each subcommand of `a && b`, `a; b`,
  `bash -c '...'` separately), `^` never matches, and quotes in the command
  appear JSON-escaped as `\\"`.
- Gemini drops any pattern its `isSafeRegExp` heuristic flags as a potential
  ReDoS: a group containing a quantifier anywhere before a later quantified
  group. So nothing below is ever written as a quantified group; repetition
  (one or two assignments, zero to two wrapper options) is unrolled instead.

Every pattern only matches curl/wget in *command position*, so benign
commands that merely mention curl/wget (`grep -r curl src/`,
`LC_ALL=C rg wget scripts/`) are not denied.

Usage:
    python3 scripts/gen-gemini-policy.py          # rewrite the example
    python3 scripts/gen-gemini-policy.py --check  # fail if it is stale
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "examples/gemini-user-policies/reviewer-network-deny.toml"

REVIEWERS = ("reviewer", "security-reviewer", "uiux-reviewer")
TOOLS = "(curl|wget)"

# End of the command word: whitespace, end of the JSON string ("), the
# backslash of an escaped quote (\"), or a single quote.
END = r"""(\s|"|\\|')"""
# Optional opening quote around the command word: JSON-escaped \" or '.
OPEN_QUOTE = r"""[\\"']*"""
# One shell word without quotes, backslashes or whitespace.
WORD = r"""[^\s"'\\]*"""
# A value: "double quoted" (JSON-escaped), 'single quoted', or a plain word.
VALUE = r"""(\\"[^"]*\\"|'[^']*'|""" + WORD + ")"
ASSIGN = r"[A-Za-z_][A-Za-z0-9_]*=" + VALUE + r"\s"
# Wrapper option: -flag or a numeric argument (timeout 30, nice -n 5).
WRAPPER_OPT = r"(-" + WORD + r"|[0-9]" + WORD + r")\s"
WRAPPERS = r"(command|exec|time|nohup|nice|timeout|stdbuf|builtin|sudo|xargs)\s"
# env argument: -option or NAME=value.
ENV_ARG = r"(-" + WORD + r"|[A-Za-z_][A-Za-z0-9_]*=" + VALUE + r")\s"

COMMAND_FORMS = {
    "bare": OPEN_QUOTE + TOOLS + END,
    "path": OPEN_QUOTE + WORD + "/" + TOOLS + END,
}

PREFIX_FORMS = {
    "": "",
    "after one assignment": ASSIGN,
    "after two assignments": ASSIGN + ASSIGN,
    "after a wrapper": WRAPPERS,
    "after a wrapper and one option": WRAPPERS + WRAPPER_OPT,
    "after a wrapper and two options": WRAPPERS + WRAPPER_OPT + WRAPPER_OPT,
    "after env": r"env\s",
    "after env and one argument": r"env\s" + ENV_ARG,
    "after env and two arguments": r"env\s" + ENV_ARG + ENV_ARG,
}

HEADER = """\
# GENERATED by scripts/gen-gemini-policy.py -- do not edit by hand.
# Regenerate with: python3 scripts/gen-gemini-policy.py
#
# Copy this file to ~/.gemini/policies/reviewer-network-deny.toml
# for Gemini CLI 0.62.0. Workspace .gemini/policies are currently non-functional.
#
# Denies curl/wget in command position for reviewer subagents: direct, quoted,
# absolute/relative path, after up to two VAR=value assignments, after env with
# up to two options/assignments, and after common wrappers (command, exec,
# time, nohup, nice, timeout, stdbuf, builtin, sudo, xargs) with up to two
# options. Benign commands that only mention curl/wget are not denied.
#
# This is a command-text guardrail, not a network sandbox. Known gaps include
# `sudo -u user curl`, `$(which curl)`, `cu""rl`, and other network-capable
# programs (python, node, nc, ssh). Use `gemini --sandbox` for a stronger
# execution boundary. scripts/test-gemini-policy.mjs checks this file against
# Gemini's real policy loader and engine.
"""


def regex_rules() -> list[tuple[str, str]]:
    rules = []
    for command_name, command in COMMAND_FORMS.items():
        for prefix_name, prefix in PREFIX_FORMS.items():
            label = f"{command_name} curl/wget" + (f" {prefix_name}" if prefix_name else "")
            rules.append((label, prefix + command))
    return rules


def toml_literal(pattern: str) -> str:
    # Multi-line literal strings take every character verbatim, including
    # single quotes, as long as the pattern contains no ''' sequence.
    if "'''" in pattern or pattern.endswith("'"):
        raise ValueError(f"pattern cannot be written as a TOML literal: {pattern}")
    return f"'''{pattern}'''"


def render() -> str:
    blocks = [HEADER]
    for subagent in REVIEWERS:
        blocks.append(
            f"""
[[rule]]
name = "Deny {subagent} curl/wget prefixes"
subagent = "{subagent}"
toolName = "run_shell_command"
commandPrefix = ["curl", "wget"]
decision = "deny"
priority = 900
"""
        )
        for label, pattern in regex_rules():
            blocks.append(
                f"""
[[rule]]
name = "Deny {subagent} {label}"
subagent = "{subagent}"
toolName = "run_shell_command"
commandRegex = {toml_literal(pattern)}
decision = "deny"
priority = 901
"""
            )
    return "".join(blocks)


def main(argv: list[str]) -> int:
    expected = render()
    if argv[1:] == ["--check"]:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != expected:
            print(
                f"[fail] {OUTPUT.relative_to(ROOT)} is stale or hand-edited; "
                "run: python3 scripts/gen-gemini-policy.py",
                file=sys.stderr,
            )
            return 1
        print(f"[ok] {OUTPUT.relative_to(ROOT)} matches scripts/gen-gemini-policy.py")
        return 0
    if argv[1:]:
        print("usage: gen-gemini-policy.py [--check]", file=sys.stderr)
        return 2
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(regex_rules())} regex rules per reviewer)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
